### ISSUE TITLE
Reloading, or injecting new, aol.properties in modules of a parent POM

### ISSUE THREAD

**Issue by abiggerhammer** [maven-nar/nar-maven-plugin#122]
I'm responsible for a couple of legacy C++ projects with their own ideas about what shared library extensions ought to be, and for legacy reasons those ideas don't get to change. I'm able to get around this with nar-maven-plugin by creating an aol.properties file for each project to define an appropriate value for, in this case, amd64.Linux.gpp.shared.extension. However, when I try to build the two projects as child modules of a parent project, only one aol.properties file is ever read (that of the first child module built); the second module reuses the properties from the first one. Even if I explicitly set a `nar.aolProperties` property in each child POM to point to the file each one needs, that setting is not honored in the second child module.

I notice that in NarProperties.java there's a static method, `.inject()`, that is meant to overwrite existing AOL properties, but it doesn't appear like this method is used in any mojo. Am I missing something?

**Comment by ctrueden** [comment]
@abiggerhammer With the merge of #251 thanks to @hboutemy, it should now be possible to override `aol.properties` the way you wanted. Please follow up here if you still have time and interest!

**Comment by ctrueden** [comment]
Presuming fixed. Please reopen if not.
