### ISSUE TITLE
SNAPSHOT dependencies in 3.2.0

### ISSUE THREAD

**Issue by vnd** [maven-nar/nar-maven-plugin#140]
There might be a regression between 3.1.1-SNAPSHOT and 3.2.0 that happens while building some C/C++ code using fetched SNAPSHOT component from a remote repository.

If 3.2.0 is used, there're only folders like "Utils-1.0-20141010.153257-18-noarch/" inside "target/nar" folder and as a result there's a compilation error: "NAR: unable to locate include path: .../target/nar/Utils-1.0-SNAPSHOT-noarch/include".

If I manually set version of nar-maven-plugin to 3.1.1-SNAPSHOT inside pom.xml there're now two copies of dependent component: one named as above and another named like "Utils-1.0-SNAPSHOT-noarch/" and compilation is successful.

**Comment by ctrueden** [comment]
@dugilos You also mentioned that you stumbled across this issue, or some variant. Is it still a problem? And does your PR #161 (now merged) fix it?

**Comment by dugilos** [comment]
I would say that my PR fix it.
The issue went from <code>artifactResolver.resolve(dependency, remoteArtifactRepositories, getLocalRepository());</code> in <code>AbstractDependencyMojo.downloadAttachedNars(List<AttachedNarArtifact> dependencies)</code> which modifies the version in AttachedNarArtifact object for SNAPSHOT artifacts and set the "real" version from web repositories with timestamp number in replacement of "SNAPSHOT" (this is done only if the artifact is not in the local maven repository and then must be download), and then when using the same list of AttachedNarArtifact to call <code>AbstractDependencyMojo.unpackAttachedNars( List<AttachedNarArtifact> dependencies )</code> after that, the folder created by unpackAttachedNars contained the timestamp number in place of "SNAPSHOT".

Exemple from the first comment of the issue:
there're only folders like "Utils-1.0-20141010.153257-18-noarch/" inside "target/nar" folder and as a result there's a compilation error: "NAR: unable to locate include path: .../target/nar/Utils-1.0-SNAPSHOT-noarch/include".

The call of downloadAttachedNars and unpackAttachedNars with the same list was done in AbstractDependencyMojo.narExecute which was called by a lots of Mojo.

What I did is that AbstractDependencyMojo no longer download and unpack dependencies, it only list them, and it is different Mojo which download or unpack dependencies, avoiding to use the same list (appart in NarAssemblyMojo which is independant, it calls downloadAttachedNars and unpackAttachedNars but before calling unpackAttachedNars I get again the artifact list not modified by downloadAttachedNars).
