### ISSUE TITLE
Full path in log

### ISSUE THREAD

**Issue by khmelevskikh** [maven-nar/nar-maven-plugin#158]
Hi,
We have issue with logs when we use this plugin.
In logs of running application we see full path to file on machine where was made compilation. File name is displayed using _FILE_ c defined macro

for example
if we compile the code by giving complete path to gcc
>  gcc -c /u02/dir/dir2/dir4/sources/foo.cc

this will show complete path to file in logs
>  "/u02/dir/dir2/dir4/sources/foo.cc"

but if we do "cd /u02/dir/dir2/dir4/sources/" and  say "gcc -c foo.cc"
in logs we see only file name.

How can we execute "gcc" without full path to source file? Maybe we can set dir for sources?

And the real problem is that if we take this compiled binary and execute it on other server, it will shows the same full path (from evn where we've compiled it) for us in logs for example.
Is it possible to add any option like workDir in plugin configuration?

**Comment by ctrueden** [comment]
See also [this thread on the maven-nar list](https://groups.google.com/d/msg/maven-nar/RdzHuPQaHBI/WGo3KtzwMOAJ).

Unfortunately, I don't know the answer to your question, nor do I have time to research it right now. But if you dig into the code and find a solution, patches are very welcome!

**Comment by dmitrykirsanov** [comment]
Hello,
If ``__FILE__`` macro in source code is used for logging, its output will depend on compilation command. For example, if we use command:
``gcc -c /u02/dir/dir2/dir4/sources/foo.cc``
we'll get below log:
> /u02/dir/dir2/dir4/sources/foo.cc: "log message"

but for command:
``gcc -c foo.cc``
log will be
> foo.cc: "log message"

So, to resolve this issue compilation command should be executed in the same directory where source file located. 
Plugin uses objectdir as working directory. I think it should use directory with sources as working.
For example, it can be done if add some modifications to _compile_ method of CommandLineCompiler.java. Something like below:
```java
String objectFile = outputDir + File.pathSeparator + getOutputFileNames(sourceFiles[j], null)[0];
String baseSourceName = FilenameUtils.getBaseName(sourceFiles[j]);
String workDir = FilenameUtils.getPath(sourceFiles[j]);
commandlineSuffix.add(getInputFileArgument(outputDir, baseSourceName, 0));

for (final String endArg : endArgs) {
    commandlineSuffix.add(endArg);
}

commandlineSuffix.add("-o");
commandlineSuffix.add(objectFile);

ArrayList<String> commandline = new ArrayList<String>(commandlinePrefix);
commandline.addAll(commandlineSuffix);
final int ret = runCommand(task, new File(workDir), commandline.toArray(new String[commandline.size()]));
```

**Comment by GregDomjan** [comment]
It is worth noting that there have been changes in this area and your note appears to be based on older code. 

In the case where there are multiple files with the same name,  the output of __FILE__ macro could be confusing if none of the path was used.
Perhaps the working dir could be set to the "source" folder, or language specific source folder.  This would remove the non project detail of the root path for some compilers.

However, if multiple source locations where used this could remain confusing
ie.  
```
     /base/project/src/main/cpp/somefile.cpp
     /base/project/target/generated/cpp/somefile.cpp
     /base/shared/cpp/somefile.cpp
```

So we get to a point where it is perhaps more process heavy to automatically identify how far up a folder structure is reasonable to ensure that we don't introduce confusion.

Still needs further discussion on possible configuration options and defaults.

Making a setting to enable/disable this 'compile from minimal path' might be appropriate.
Could we then make an assumption that a minimum relative path could default to the ```project.baseDir  ``` but also be configurable, so in the case above ```${project.baseDir}/..``` could be used, and in the original example ```${project.baseDir}/dir/dir2/dir4/sources``` could be used.

sourceFiles are resolved with full path earlier in the process, there would need to be some re-factoring.

**Comment by dmitrykirsanov** [comment]
There is ``sourceDirectory`` parameter in Compiler class. Can it be used as working directory? The rest part of path to source files may stay with file in compiler command line. In this case if I have multiple sources with the same name I can point this param to some common dir for both files. It should eliminate the risk of confusing with file names. For example, I have two files in two directories:
```
    /base/project/src/main/dir/dir1/somefile.cpp
    /base/project/src/main/dir/dir2/somefile.cpp
```
If I set `sourceDirectory` to `/base/project/src/main/dir` I get in logs below for each file:
```
dir1/somefile.cpp: "some message"
dir2/somefile.cpp: "some other message"
```
Or if all my source files are located in one folder I can set the `sourceDirectory` param directly to this folder and I get only source file name in logs.

On the other hand, if my above suggestion cannot be convenient for some reason we can discuss other options. I don't mind if we will have some 'compile from minimal path' parameter that we can enable/disable.For example, it can work the same way as I described above with `sourceDirectory`.

**Comment by dmitrykirsanov** [comment]
I've linked sourceDirectory parameter with compiler working directory. You may see details in below commit:
https://github.com/dmitrykirsanov/nar-maven-plugin/commit/42c49f216c85311891d3980b1ebb20161338eef7
Such solution is appropriate for us. What do you think about it?
