### ISSUE TITLE
Header only lib produces a shared library

### ISSUE THREAD

**Issue by markjohndoyle** [maven-nar/nar-maven-plugin#159]
We have a header only module with no source files (.cpp).

The nar plugin is producing the expected nar and noarch nar but it's also producing a shared library (.so or .dll). I'm not sure what's in the library or whether that's expected behaviour for nar.

The following property doesn't seem to affect the output:
```xml
<properties>
        <nar.includefilesonly>true</nar.includefilesonly>
</properties>
```

Thanks!

**Comment by dproteus13** [comment]
Which property? Looks like it got deleted from your post accidentally. ..

**Comment by markjohndoyle** [comment]
Oops, fixed!

**Comment by ctrueden** [comment]
From the documentation: `TBD If you set maven.nar.includefilesonly to true the compilation step will be skipped. This flag can be used if you want to distribute a library that only contains pure abstract classes in include files.`

The "TBD" stands for "to be developed", which means the feature does not yet exist. It was a feature the original author of NAR wanted to add, but never got around to doing. I verified this using `git grep -i includeFilesOnly`—the only hits are in the documentation.

**Comment by markjohndoyle** [comment]
TBD noted for future.

Previous versions of the nar plugin wouldn't produce any output if there were only headers so you'd have to add a dummy class file. The latest version seems to produce everything regardless.

I guess that's just the way it is presently. If I find some time I'll look into it.

**Comment by ctrueden** [comment]
> If I find some time I'll look into it.

Thanks, that would be awesome!

**Comment by markjohndoyle** [comment]
I've since noticed that if you don't have a libraries section in your nar plugin configuration then you will only get a no-arch artefact (assuming you have includes). So this isn't a problem afte rall.

**Comment by ctrueden** [comment]
@markjohndoyle So, should we close this issue?

**Comment by markjohndoyle** [comment]
I think so, Curtis; as far as I am concerned anyway!
