### ISSUE TITLE
Linker.getVersion change PATH from System PATH on Windows

### ISSUE THREAD

**Issue by pauldaustin** [maven-nar/nar-maven-plugin#164]
The Linker.getVersion does not include the toolPath defined on a <linker><toolPath>... configuration.

This means if the system PATH environment does not include the directory that link is in then the build fails.

This also means it's not possible to build multiple architectures if they require different link.exe for 32 vs 64 bit

**Comment by ctrueden** [comment]
You fixed this as part of your work on #170 right?

**Comment by pauldaustin** [comment]
Yes the Msvc code does the detection of the versions rather than running the link.exe command to find the version.
