### ISSUE TITLE
MS Visual Studio Auto configuration

### ISSUE THREAD

**Issue by pauldaustin** [maven-nar/nar-maven-plugin#165]
I'm working on a patch that will simplify the setup of MSVC projects.

The patch adds the following configuration section.

```
<msvc>
  <version>10.0</version>
  <windowsSdkVersion>7.1A</windowsSdkVersion>
</msvc>
```

The configuration allows defining the MS Visual Studio version number.
This will then auto detect the Visual Studio Home. If the version is not
specified it will look for the VSxxxCOMNTOOLS environment variables to
see which
versions exist and use the maximum available version.

The configuration also allows selecting the windowsSdkVersion. If not
specified it will look in the C:\Program Files (x86)\Microsoft
SDKs\Windows or C:\Program Files (x86)\Windows Kits for available
versions.

The linker and compilers will then be configured with default includes
and library paths from both the visual studio and windows sdk homes.

I'm almost ready to create a pull request for this feature. I just need to verify the amd64 compilation and linking.

**Comment by ctrueden** [comment]
Sounds great, @pauldaustin. Thanks for the update!

**Comment by eyalg1972** [comment]
Was it created? If so- how can I use it?

**Comment by ctrueden** [comment]
@eyalg1972 It might have been one (or more) of: #166, #168, #170, #173, #174.

Regardless, I'm closing this issue, since it's very old, and probably addressed, and even if not, it's not moving forward anymore, nor could anyone else feasibly pick it up to work on it.
