### ISSUE TITLE
Javadoc errors when building with JDK 1.8

### ISSUE THREAD

**Issue by jgeorgeson** [maven-nar/nar-maven-plugin#171]
A common issue with JDK 8 is the stricter lint filter in javadoc. The maven-javadoc-plugin has an open issue to directly support configuration of the doclint filter but there's no release targeted for a fix.

https://jira.codehaus.org/browse/MJAVADOC-387

Seems nar-maven is affected by this too. Can workaround by adding "-Dadditionalparam=-Xdoclint:none" on command-line.

**Comment by ctrueden** [comment]
Thanks for the report. Although I would love to eventually clean up all the javadoc to conform to Java 8 doclint standards, for now I pushed a workaround.
