### ISSUE TITLE
Test compile should link static libraries

### ISSUE THREAD

**Issue by Tubeliar** [maven-nar/nar-maven-plugin#175]
In the file NarTestCompileMojo.java at the time of linking (line 278 in my version) it says certain library types should not be linked. The comments say about static libraries " there is no need to link to the test application the static libraries already included in the tested library". While it makes sense not to test the library itself, a test program could perform operations defined on data structures defined in them so they should be linked.

**Comment by ctrueden** [comment]
Would you care to [contribute a patch](https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute)?

**Comment by Tubeliar** [comment]
Done!
