### ISSUE TITLE
Fails on latests master branch - looks for gcc in Visual studio directories.

### ISSUE THREAD

**Issue by markjohndoyle** [maven-nar/nar-maven-plugin#190]
Hi all,

I've built the latest snapshot master branch and get the following error when compiling a project that uses gcc. I understand it's the snapshot but I thought it is worth tracking.

OS: Windows 10 x64
λ gcc --version
gcc.exe (Rev5, Built by MSYS2 project) 4.9.2

ERROR:
------------------------------------------------------------------------
Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.4-SNAPSHOT:nar-compile (default-nar-compile) on project libdispatch: NAR: Compile failed: Could not launch C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\gcc: java.io.IOException: Cannot run program "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\gcc" (in directory "C:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\obj\amd64-Windows-gcc"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]

**Comment by markjohndoyle** [comment]
Looks like it's related to this new piece of code in Compiler.java

// tool path
    if (this.toolPath != null) {
      compilerDef.setToolPath(this.toolPath);
    } else {
      mojo.getMsvc().setToolPath(compilerDef,getLanguage());
    }

**Comment by markjohndoyle** [comment]
I'll see if your commit helps, Greg.  I did a quick hack to check what happens if we bypass setting that MSVC toolpath myself and the CreateProcess still failed; it was a quick check though.

**Comment by markjohndoyle** [comment]
@GregDomjan 
Yeah, unfortunately, it still fails, I've extracted the command lines used from the current build and a build from before the msvc branch merge.

## Compiler command lines
### Latest master branch build
`gcc -mthreads -c -mconsole -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\szip-2.1.0-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\zlib-1.2.8-noarch\i nclude -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\hdf5-1.8.14-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\core-4.3.2-noarch\include -IC:\Users\mark j\code\netcdf-c-nar\libdispatch\src\main\include "-isystemC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include" "-isystemC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmf c\include" "-isystemC:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" "-isystemC:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um" "-isystemC:\Program Files (x86)\ Windows Kits\10\Include\10.0.10240.0\shared" "-isystemC:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\winrt" -o C:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\obj\amd64-W indows-gcc\dattput.244e1e95.o C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dattput.c
gcc.exe: error: C:Usersmarkjcodenetcdf-c-narlibdispatchsrcmainc++dattput.c: No such file or directory
gcc.exe: fatal error: no input files
compilation terminated.`

You can see lots of MSVC system includes and some corruption to the command, probably sue to spaces.


### Pre MSVC build
`gcc -mthreads -c -mconsole -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\core-4.3.2-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\hdf5-1.8.14-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\zlib-1.2.8-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\szip-2.1.0-noarch\include -IC:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\include C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dattget.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dcopy.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\denum.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dopaque.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dtype.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dvarget.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\nc.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\nclist.c C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\ncuri.c`

This one works fine.


Maybe there is a issue arising from non-Visual Studio environments on Windows, e.g. Mingw, Msys2.

**Comment by GregDomjan** [comment]
Ack, that's a bit horrible to read.  
Additional Windows SDK folders could be added only in msvc build I guess, believe that isn't actually the problem.

The other recent change for solving unique file name issue seems to be related.
Looks like something has  taken out the \ in the filename, possibly a quoting issue.

```
 -o C:\Users\markj\code\netcdf-c-nar\libdispatch\target\nar\obj\amd64-Windows-gcc\dattput.244e1e95.o 
C:\Users\markj\code\netcdf-c-nar\libdispatch\src\main\c++\dattput.c 

error: C:Usersmarkjcodenetcdf-c-narlibdispatchsrcmainc++dattput.c: No such file or directory
```

I'm not sure exactly why it's being handled differently now, can check further soon. 
Related - From GccCompatibleCCompiler.java 

```
  @Override
  protected String getInputFileArgument(final File outputDir, final String filename, final int index) {
    switch (index) {
      case 0:
        return "-o";
      case 1:
        final String outputFileName = getOutputFileNames(filename, null)[0];
        final String objectName = new File(outputDir, outputFileName).toString();
        return objectName;
    }
    return filename;
  }
```

**Comment by markjohndoyle** [comment]
This might actually be a PATH issue. 

The PATH used to execute the CCTask in CUtil runCommand is different to my system's environment. The CCTask version just has a few MSVC paths in there which is why the process cannot find gcc.

**Comment by markjohndoyle** [comment]
NarCompileMojo.java +218

getMsvc().configureCCTask(task);

This line seems to be the cause of the environment configuration, which affects gcc compilers.

I'm guessing one cannot simply remove that line though :)
