### ISSUE TITLE
Need ability to skip automatic dependency linkage

### ISSUE THREAD

**Issue by dmitrykirsanov** [maven-nar/nar-maven-plugin#199]
Hello,
If I have in my project several dependency libraries, nar plugin will automatically download them from repository, unpack and add to linker command line. 
I can define order of these libraries with narDependencyLibOrder parameter. But they always will be at the beginning of linker command. What if one dependency library need to be linked after some nondependency library? 
That's why I am asking to add some option (probably boolean) to linker configuration for skipping this automatic linkage. In this case plugin will download and unpack library the same way and I can set it in a right place by configuring linker.

**Comment by dmitrykirsanov** [comment]
I can offer such solution:
https://github.com/dmitrykirsanov/nar-maven-plugin/commit/0d2c32e72955e50f5af10233aec6f24d1141fddb

**Comment by ctrueden** [comment]
Beautiful. Care to file a PR?
