### ISSUE TITLE
on MacOS, jni library has output suffix "jnilib" but the generated NarSystem.java looking for dylib

### ISSUE THREAD

**Issue by stonewell** [maven-nar/nar-maven-plugin#213]
on MacOS, jni library has output suffix "jnilib" but the generated NarSystem.java looking for "dylib"

**Comment by ctrueden** [comment]
Actually, the `NarSystem` [tries both, depending on the JDK version](https://github.com/maven-nar/nar-maven-plugin/blob/3f8c317a76b1cb24485a41cbb73791d8f2a2dcbb/src/main/java/com/github/maven_nar/NarSystemMojo.java#L97-L101).

See also discussion #184 and #183.

**Comment by stonewell** [comment]
So, looks like my plugin version is old, I installed from the maven central
repository, where should I found the latest version?

Thanks

On Mon, Feb 29, 2016, 11:25 Curtis Rueden <notifications@github.com> wrote:

> Actually, the NarSystem tries both, depending on the JDK version
> <https://github.com/maven-nar/nar-maven-plugin/blob/3f8c317a76b1cb24485a41cbb73791d8f2a2dcbb/src/main/java/com/github/maven_nar/NarSystemMojo.java#L97-L101>
> .
>
> See also discussion #184
> <https://github.com/maven-nar/nar-maven-plugin/pull/184> and #183
> <https://github.com/maven-nar/nar-maven-plugin/pull/183>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maven-nar/nar-maven-plugin/issues/213#issuecomment-190345180>
> .
>
-- 
这世间，唯有梦想与*好姑娘*不可辜负

**Comment by ctrueden** [comment]
> where should I found the latest version?

https://github.com/maven-nar/nar-maven-plugin/wiki/Testing#testing-the-latest-snapshots

I have been too busy to cut a new release lately, but if you confirm that the current master branch works well for you, I can do a release later this week. Just let me know.

**Comment by stonewell** [comment]
cool, it works
Thank you

Curtis Rueden <notifications@github.com>于2016年2月29日周一 下午12:03写道：

> where should I found the latest version?
>
>
> https://github.com/maven-nar/nar-maven-plugin/wiki/Testing#testing-the-latest-snapshots
>
> I have been too busy to cut a new release lately, but if you confirm that
> the current master branch works well for you, I can do a release later this
> week. Just let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maven-nar/nar-maven-plugin/issues/213#issuecomment-190359030>
> .
>
-- 
这世间，唯有梦想与*好姑娘*不可辜负

**Comment by ctrueden** [comment]
Thanks for the feedback. I released `3.3.0`. It should be available from Central very shortly.
