### ISSUE TITLE
VisualStudio required

### ISSUE THREAD

**Issue by mr-raphael-martin** [maven-nar/nar-maven-plugin#234]
Using NAR Plugin version 3.4.0 on a Windows 7 platform **where Visual Studio has never been installed**, Nar plugin always try to run the command "cmd.exe /X /C "link /?", i.e. try to check if MSVC++ is installed.
So it seems impossible to work with MINGW/GCC
You can try to force, platform, os, linker name or directly AOL in your POM, all these options are ignored, in the early goal VALIDATE.
To solve the problem, I had to get back to NAR 3.2.3 version. What a pity... I am quite desappointed because I used NAR plugin for years now...

**Comment by ctrueden** [comment]
This is definitely a bug, not intended behavior. A PR fixing it would be most warmly welcomed. If you do not have time, then there is nothing wrong with continuing to use 3.2.3 for now.

**Comment by mr-raphael-martin** [comment]
Hi Curtis
Thanks for your quick answer.
I will try to have a deeper look inside the code. I isolated already that the problem come from the initialization of the Nar mojos, all derivated from the same abstract Nar mojo. Unfortunately in the private method checking for MSVC default parameters, the case of not having any MSVC installed is not (correctly)implemented.
I will keep on investigating...
Le 10 juin 2016 23:07, Curtis Rueden <notifications@github.com> a écrit :This is definitely a bug, not intended behavior. A PR fixing it would be most warmly welcomed. If you do not have time, then there is nothing wrong with continuing to use 3.2.3 for now.

**Comment by dugilos** [comment]
Hello all,
After a long pause I recently updated the plugin for my projects and I ran on the same error, so I corrected it and sent the pull request #238

**Comment by ctrueden** [comment]
I assume the merge of #238 fixes this issue. If not, please reopen.
