### ISSUE TITLE
Linker default dependency Lib Order

### ISSUE THREAD

**Issue by manu4linux** [maven-nar/nar-maven-plugin#236]
This is to follow up on my post on mailing list here https://groups.google.com/forum/#!topic/maven-nar/-scI_A58H5U

If I am not wrong it looks like file AbstractDependencyMojo.java and in getNarArtifacts() it gets artifacts with `Set<Artifact> artifacts = getMavenProject().getArtifacts();` and then it filter it..

And in old code it looks like NarManager.java getNarDependencies() does it by `for ( Iterator i = getDependencies( scope ).iterator(); i.hasNext(); )`  which in turn calls `List<Artifact> MavenProject.getCompileArtifacts();`

So difference is in not using deprecated `List<Artifact> MavenProject.getCompileArtifacts();`

That said, issue is that as a user I do not expect to give <narDependencyLibOrder> list order unless its an exception from the typical C/CPP linker behavior lib order to be.

I propose solution to have a default Dependency Lib Order which will only be invoked by a switch in Linker config.

I will soon be doing a pull request with my patch.

**Comment by manu4linux** [comment]
Thanks for the suggestion @ctrueden ..I have cleaned up the code now...

**Comment by ctrueden** [comment]
@manu4linux Hmm, there are now three commits all with the same commit message. I will try to squash them myself, in the interest of minimizing everyone's time. But in future it would really be good for you to learn how to do `git rebase -i`. See e.g. http://imagej.net/Git#Rewriting_history

**Comment by ctrueden** [comment]
I merged #237, so this issue is resolved.

**Comment by manu4linux** [comment]
Excellent,  thank you @ctrueden !
