### ISSUE TITLE
Not working with Java 8, Invalid byte tag

### ISSUE THREAD

**Issue by ccjason** [maven-nar/nar-maven-plugin#240]
If one uses maven-nar with Java 8, the build will fail with a "Invalid byte tag in constant pool: 18" message.  The problem apparently is that the version of BCEL that nar uses does not support Java 8.  So right now Java 8 users can not use nar.  This is a pretty big audience.  There are various work arounds, but given how popular Java 8 is, we should get this fixed.

BCEL 6.0 will support Java 8.  In fact the BCEL 6.0-SNAPSHOT does work.  But unfortunately BCEL 6.0 has not been released in the 2+ years since this shortcoming was fixed in 6.0-SNAPSHOT.  Something is holding up that release.  And unfortunately 6.0-SNAPSHOT is not published to Maven Central, so everyone that needs to build a nar project on Java8 also needs to build BCEL or become part of a team that uses a Maven server that contains a copy that someone else built.  Both seem like a high bar for many of us and our extended builder community.

So how can we fix this for our community?

- Can we have the BCEL SNAPSHOT-6.0 published to mvn central? (probably not)
- Can we help resolve whatever is preventing bcel 6.0 from being released?
- Can we eliminate use of bcel ? 
- Can we let pom authors work around this if their project is getting hung up?  (The author of the pom almost certainly knows which .class files contain native code and doesn't benefit much from nar trying to determine this automatically.)
- - Can the javah goal be updated to look in the pom file for a list of classes to run javah on?
- - or can the javah goal be updated to instead run javah.bypass.sh if it exists?

**Comment by ctrueden** [comment]
Actually, it looks like BCEL 6.0 _was_ released a few days ago:

* http://search.maven.org/#artifactdetails%7Corg.apache.bcel%7Cbcel%7C6.0%7Cjar

Furthermore, it seems that NAR does not depend on `org.apache.bcel:bcel`, but rather on some fork: `com.google.code.findbugs:bcel-findbugs:6.0`.

@ccjason Could you please try replacing the latter dependency with the freshly released `org.apache.bcel:bcel:6.0`, and see whether that solves the issue for you?

If so, we can simply update the dependency! If not, let us know of any problems in this thread here.

**Comment by ctrueden** [comment]
@ccjason Any news? Does it work if you depend on `org.apache.bcel:bcel:6.0`?

**Comment by ctrueden** [comment]
@ccjason I tried testing this myself, but cannot reproduce this issue on OS X with Java 8 1.8.0_77, nor on Linux with Java 1.8.0_91. If the issue still occurs with `org.apache.bcel:bcel:6.0` with your project, could you please provide an MCVE illustrating the issue?

**Comment by ccjason** [comment]
Thank you Curtis.  You are correct.   Everything works without
complications now.

**Comment by ctrueden** [comment]
> Thank you Curtis.  You are correct.   Everything works without complications now.

@ccjason Thanks for the feedback.

It was not clear to me from your reply whether you needed to change the dependency to `org.apache.bcel:bcel:6.0`, or whether it works for you with the existing `com.google.code.findbugs:bcel-findbugs:6.0`. But regardless, I updated the dependency to the official BCEL 6.0 release, since that seems more correct to me.
