### ISSUE TITLE
option of full path to filenames added for gcc builds

### ISSUE THREAD

**Issue by manu4linux** [maven-nar/nar-maven-plugin#244]
we see that all the debug string filenames with in executable now only have relative path to main. for example `/base/project/src/main/c/somefile.c` would show as `c/somefile.c`
Since our project use a static dependency libs, let say file from `/base/project2/src/main/c/someotherfile.c` will resolve to `c/someotherfile.c` causing GDB debugging issues. 

We have 14 million lines of code spread out all over the place. Our build agents end up with paths like this:

```
/usr/local/teamcity/buildagent/work/41ae010f80e2cbba/c/cs_timer.c, 
/usr/local/teamcity/buildagent/work/41ae010f80e2cbba/c/cs_sequence.c
```

for files physically at 
/home/user/server/modules/c-libs/**cs_timer/src/main**/c/cs_timer.c
/home/user/server/modules/c-libs/**cs_sequence/src/main**/c/cs_sequence.c

In our .gdbinit file, we can map `/usr/local/teamcity/buildagent/work/41ae010f80e2cbba/` to the top level of our source (as in `set substitute-path /usr/local/teamcity/buildagent/work/41ae010f80e2cbba/ /home/user/server/modules/c-libs/cs_timer/src/main`) and gdb can find the sources. But, without the full path and just `c/cs_env.c` or `c/cs_super.c` we’d have to have individual mapping for each file. That’s unworkable for us.

if I am not wrong Behavior in old `maven-nar-plugin`  seem to give full path which made it easy for GDB to find them.

FYI, pls see https://groups.google.com/forum/#!topic/maven-nar/sIBkEOdjDfA

**Comment by ctrueden** [comment]
@manu4linux Did you [bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git#Binary-Search) the code to find the commit where the issue was introduced? If you can do that, we can ask the author of the offending patch for their opinion on how best to resolve it.

**Comment by manu4linux** [comment]
Thanks for the suggestion @ctrueden . I did, did github `blame` and found the @dmitrykirsanov had the changes around the code i am interested for this issue.

I made #245 pull request as per the short NAR mail group conversation i had with @dmitrykirsanov
at https://groups.google.com/forum/#!topic/maven-nar/sIBkEOdjDfA

i would request you to merge said #245 pull once you have confidence in it, may be once **dmitrykirsanov** reviews it.

![image](https://cloud.githubusercontent.com/assets/15072540/18057857/f377f4c6-6dce-11e6-961e-9da48ce10929.png)
