### ISSUE TITLE
Release 3.5.1 request

### ISSUE THREAD

**Issue by karypid** [maven-nar/nar-maven-plugin#247]
It seems like there is a fix in master which restores the ability to use GCC compilers on Windows:
https://groups.google.com/d/msg/maven-nar/Orm_I0tL4pE/PXG8oSyaAgAJ

There are several resources online that explain how to use gcc by setting the <name> tag in linker/c section of the configuration, so the fact that it hasn't worked since 3.2.3 makes it a challenge for new users to adopt using this plugin.

Any chance there is a 3.5.1 release to restore this functionality? Right now it's either use 3.2.3 for me, or build a 3.5.0-personal version from master (to use privately)...

**Comment by ctrueden** [comment]
Released! [com.github.maven-nar:nar-maven-plugin:3.5.1](https://oss.sonatype.org/#nexus-search;gav~com.github.maven-nar~nar-maven-plugin~3.5.1~~)

See also the [corresponding maven-nar list thread](https://groups.google.com/d/msg/maven-nar/Orm_I0tL4pE/IRZot77CCQAJ).
