### ISSUE TITLE
question: how to make maven-failsafe-plugin work when a project depends on a nar artifact?

### ISSUE THREAD

**Issue by dmakarov** [maven-nar/nar-maven-plugin#268]
I have a project that uses `maven-failsafe-plugin` to run integration tests.  This project depends on another project that builds a native shared library and a corresponding jar file using `nar-maven-plugin`.  When integration tests run, `NarSystem.loadLibrary()` fails to load the needed native library, because the path to the library wasn't added to `java.library.path` property as would be the case if `nar-integration-test` were used.  However, it can't be used, because `failsafe:integration-test` goal is being built.  What is the proper way to set up a project that depends on a nar artifact in such case?

**Comment by ctrueden** [comment]
Can you pass the `java.library.path` to the failsafe plugin's `argLine` as a JVM parameter?

**Comment by dmakarov** [comment]
Maybe. I don't know. But is there a way to extract the path to the native library within a pom programmatically so that the proper path is added to java.library.path? Also it looks like nar-integration-test sets the environment variable DYLD_something with the path in addition to augmenting java.library.path.

**Comment by ctrueden** [comment]
The closest thing I know of is the [`native-lib-loader` integration](https://github.com/maven-nar/nar-maven-plugin/wiki/Native-Library-Loader), which will load the native libs out of JAR/NAR files on the classpath... but note that it uses `System.load` and hence cannot support native dependencies.

**Comment by eyalg1972** [comment]
I think it is the same issue that I am wrote about the MacOS- that the DYLD_LIBRARY_PATH does not work anymore. I will try to implement a call to System.load instead

**Comment by dmakarov** [comment]
I do use `org.scijava:native-lib-loader` in the project that builds the native libraryand it works fine for `nar:nar-integration-test` goal in another project that depends on the former one (the one that builds the library).  However, as I mentioned, `failsafe:integration-test`  fails in `NarSystem.loadLibrary();` because `java.library.path` doesn't contain path to `target/...` where the necessary .dylib file is extracted from the nar artifact.  I don't know if it's even necessary to have `DYLD_LIBRARY_PATH` set.

**Comment by eyalg1972** [comment]
Does it need to load dylib or jni lib ?

Eyal

**Comment by dmakarov** [comment]
In my setup I use dylib.  Initially, I started with jnilib, but then I couldn't make `native-lib-loader` to work with jnilib and I changed the type of native library in pom to shared, which creates a dylib.  From why point of view, there's no difference whether it's packaged as jnilib or dylib, as long as everything works.  However, the instructions in nar-maven-plugin is so difficult to understand, that it's mostly through trial and error I ended up generating dylib.  Ultimately, I need the library to be created on all major platforms Linux, MacOS, and Windows, and I don't care how it's packaged, as long as all versions are bundled in a single NAR artifact.

**Comment by ctrueden** [comment]
> the instructions in nar-maven-plugin documentation are so difficult to understand

I agree. It's one of several reasons I also find it difficult to work on NAR-related projects. Help from the community to improve the documentation is supremely welcome.
