### ISSUE TITLE
UnsatisfiedLinkError if java.io.tmpdir contains relative path

### ISSUE THREAD

**Issue by mschoudry** [maven-nar/nar-maven-plugin#289]
Hi,
If there is a relative path set in java.io.tmpdir, there is an error 
java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library.
Apparently in generated NarSystem.java the default JNI extractor extracts the  dlls in to java.io.tmpdir and then System.load(extracted.getPath()); is used to load the libaray. System.load requires absolute path to load the library.

The simple fix seems to be System.load(extracted.getAbsolutePath());

Environment:
OS=Windows-7
JDK=7

Regards,

**Comment by ctrueden** [comment]
Fixed by #290. Thank you @mschoudry!
