### ISSUE TITLE
secondary execution combines primary execution options when "append" options is used

### ISSUE THREAD

**Issue by AnnDinKC** [maven-nar/nar-maven-plugin#300]
There is a bug where the cpp options in secondary executions do not append to the default cpp options when the default and secondary executions are all defined in the same pom.xml file. 

Please refer to the following pull request, containing an integration test demonstrating this case.
https://github.com/maven-nar/nar-maven-plugin/pull/299

**Comment by bchiodo** [comment]
@AnnDinKC  Can this be closed now that the referenced PR has been merged?
