### ISSUE TITLE
Support deployment of artifacts from multi-platforms/multi-aol's:

### ISSUE THREAD

**Issue by mangrer** [maven-nar/nar-maven-plugin#304]
## Problem Scenario:

We support the deployment of artifacts from multiple platforms with multiple different AOL's. 

How maven-nar is blocking us to attain the goal above is, maven-nar provides a nar.properties file, stored in an aol agnostic .nar file but contains aol specific information. (In this scenario, assume we have aol specific properties like output file name is overridden for the endstate). 

To explain with an example, say project A deploys an artifact in windows with an aol amd64-Windows-gpp, during packaging goal a nar.properties file is developed and  deployed to the repo contained in A-<version>.nar, when the same project deploys an artifact in linux with an aol amd64-Linux-gpp, a new nar.properties file packaged in nar (A-<version>.nar) is deployed to the repo & overwrites existing amd64-Windows-gpp nar file. So for a consumer B that tries to consume A in amd64-Windows-gpp aol, maven-nar wouldn't be able to find aol properties from nar.properties file because the latest deploy for that artifact from a Linux aol. 

## Solution:

The solution we developed is to place nar.properties file in aol nars, so the consumers can use aol specific nar's to read aol specific information from nar.properties file. 

Other possible solution, one can work around is keeping a separate repository for each of the aol's or platforms.  

## Implementation details:

_The current state of maven-nar packaging_ where nar.properties file go,

artifact-version.nar // contains a nar.properties file with aol agnostic & aol1 specific properties (say coming from latest deploy) 
artifact-version-aol1-type.nar // contains aol1 libs
artifact-version-aol2-type.nar // contains aol2 libs

On maven-compile phase, when a downstream project tries to build with aol2 configuration, the plugin reads properties for aol2 type nar from artifact-version.nar, and fail to find aol2 specific properties.

_The proposed & implemented state of maven-nar packaging_ where nar.properties file go, 

artifact-version.nar // contains a nar.properties file with aol agnostic & aol1 specific properties say, coming from latest deploy (this is provided to be passive with older versions of plugin)
artifact-version-aol1-type.nar // contains aol1 libs + aol1 specific properties in nar.properties file
artifact-version-aol2-type.nar // contains aol2 libs + aol2 specific properties in nar.properties file.

So a downstream project that tries to build with aol2 configuration will load properties file from project-version.nar and also nar.properties file from project-version-aol2-type.nar, so its guaranteed to find aol2 specific properties in the properties file of the aol2 nar regardless of who deployed the artifact latest.

## Any passivity concerns?

The solution is passive to artifacts deployed using older versions. Artifacts built using older versions work with this version, and artifacts built using this version should work with old versions of the plugin. 

## Pull-request:

Please refer to https://github.com/maven-nar/nar-maven-plugin/pull/303 (also contains integration-tests demonstrating the scenario).

**Comment by ctrueden** [comment]
Resolved by #303.
