### ISSUE TITLE
Can't use nar plugin with Java 10 (javah is missing)

### ISSUE THREAD

**Issue by eolivelli** [maven-nar/nar-maven-plugin#313]
Hi, on Java 10 there is no javah

see:
http://openjdk.java.net/jeps/313

is there any workaround ?

**Comment by eolivelli** [comment]
I see javac has "-h" option
https://bugs.openjdk.java.net/browse/JDK-7150368

is there any way to make nar plugin use javac -h ?
or not to run javah ?

**Comment by ctrueden** [comment]
@eolivelli It is possible to override the javah executable in the `<javah>` configuration settings:
```
<javah>
<name>myjavah</name>
...
</javah>
```
For details see the [Configuration](http://maven-nar.github.io/configuration.html) documentation.

But looking at [the source](https://github.com/maven-nar/nar-maven-plugin/blob/02487b4ef1d9da37985750ade57eaf056b0f8717/src/main/java/com/github/maven_nar/Javah.java#L249), it is clear that simply putting `javac -h` there will not work; the source code probably needs a small improvement to support overriding flags as well.

**Comment by eolivelli** [comment]
[ERROR] /bin/sh: /usr/java/jdk-10/bin/javac -h: No such file or directory

org.apache.maven.plugin.MojoExecutionException: exit code: 127
    at com.github.maven_nar.NarUtil.runCommand (NarUtil.java:703)
    at com.github.maven_nar.NarUtil.runCommand (NarUtil.java:635)
    at com.github.maven_nar.NarUtil.runCommand (NarUtil.java:609)
    at com.github.maven_nar.Javah.execute (Javah.java:253)
    at com.github.maven_nar.NarJavahMojo.narExecute (NarJavahMojo.java:65)
    at com.github.maven_nar.AbstractNarMojo.execute (AbstractNarMojo.java:329)

@ctrueden I can work on a simple patch, this really blocker for me (at https://github.com/apache/bookkeeper) in order to move to jdk10 

Could you give me some hint ? 
- where/how to write a test
- new paramater name (a 'additionalParameters' in the javah tag) ?

my idea would be:
- let the user configure 'javac' instead of default 'javah' in javah/name
- let the user configure <additionalParameters>-h</additionalParameters>
- make it the defaults in jdk10 upwards (how to detect?)

like this:
`<javah>
<name>javac</name>
<additionalParameters>-h</additionalParameters)
`

**Comment by eolivelli** [comment]
Hi, this is my idea #316 

is this the right way ?

**Comment by eolivelli** [comment]
Unfortunately my idea does not work, javac is very different from javah.

I will eventually need to combine java compiler plugin with nar plugin.

If anyone has some working example please tell.

I will be back with my ides/comments

**Comment by eolivelli** [comment]
@ctrueden 

This is my proposal to fix the problem
#317

Actually the idea is to add a "skip" flag to javah, this way the user can disable it on jdk10 onwards.

Thank you

**Comment by eolivelli** [comment]
I found an alternative solution, that is to bind default-nar-javah execution to phase 'none'

This is not very comfortable but it works.
Please take into account my patch, which makes this configuration more use friendly  

```     
            <executions>
                <execution>
                    <id>default-nar-javah</id>
                    <phase>none</phase>
                </execution>
            </executions>
```

**Comment by ctrueden** [comment]
@eolivelli Great, I'm glad it was simple. And nice to hear that Java 10 integrates `javah` directly.

**Comment by GregDomjan** [comment]
For Ref https://openjdk.java.net/jeps/313

**Comment by GregDomjan** [comment]
Also for ref
```
<profiles>
	<profile>
		<id>java-9</id>
		<activation>
			<jdk>9</jdk>
		</activation>
		<build>
			<pluginManagement>
				<plugins>
					<plugin>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<compilerArgs>
								<arg>-h</arg>
								<arg>${project.build.directory}/nar/javah-include</arg>
							</compilerArgs>
						</configuration>
					</plugin>
					<!-- pending javah><skip -->
					<plugin>
						<groupId>com.github.maven-nar</groupId>
						<artifactId>nar-maven-plugin</artifactId>
						<executions> 
							<execution>
								<id>default-nar-javah</id>
								<phase>none</phase>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</pluginManagement>
		</build>
	</profile>
</profiles>
```

**Comment by devurandom** [comment]
Using the following `activation` adds support for Java 10+:
```xml
<activation>
  <jdk>[9,)</jdk>
</activation>
```

cf. https://maven.apache.org/guides/introduction/introduction-to-profiles.html#details-on-profile-activation and https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
