### ISSUE TITLE
Possible values for <option>

### ISSUE THREAD

**Issue by Adraas** [maven-nar/nar-maven-plugin#339]
Why the plugin's documentation does not specify the possible values ​​for the tag `<option>`? Where can I find out how to make it? In particular, the possible values ​​for the tag `<option>` for `<linker>` and `<c>`.

**Comment by ctrueden** [comment]
It's open-ended, because the options get fed to the named compilation tool. You can pass whatever command line parameters you want. And what you pass will depend on which compiler and linker tools you are calling.

Here is an example from the `it0034-secondary-execution-options` integration test:
```
           <cpp>
             <name>g++</name>
             <includes>
               <include>**/*.cpp</include>
             </includes>
             <options>
               <option>-D_PARENT_FLAG=0</option>
             </options>
           </cpp>
```
The `g++` executable accepts `-Dfoo=bar` syntax to assign value to variables at compile time.

Here, in the corresponding source code, the `_PARENT_FLAG` variable set above is utilized:
```
$ git grep PARENT_FLAG
it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:#ifdef _PARENT_FLAG
it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:   printf("_PARENT_FLAG is defined.\n");
it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:   printf("_PARENT_FLAG should be defined
pom.xml:               <option>-D_PARENT_FLAG=0</option>
```

Does that help?

**Comment by Adraas** [comment]
> It's open-ended, because the options get fed to the named compilation tool. You can pass whatever command line parameters you want. And what you pass will depend on which compiler and linker tools you are calling.
> 
> Here is an example from the `it0034-secondary-execution-options` integration test:
> 
> ```
>            <cpp>
>              <name>g++</name>
>              <includes>
>                <include>**/*.cpp</include>
>              </includes>
>              <options>
>                <option>-D_PARENT_FLAG=0</option>
>              </options>
>            </cpp>
> ```
> 
> The `g++` executable accepts `-Dfoo=bar` syntax to assign value to variables at compile time.
> 
> Here, in the corresponding source code, the `_PARENT_FLAG` variable set above is utilized:
> 
> ```
> $ git grep PARENT_FLAG
> it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:#ifdef _PARENT_FLAG
> it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:   printf("_PARENT_FLAG is defined.\n");
> it0034-secondary-execution-options-hello-world/src/main/c++/HelloWorldDualExecutions.cpp:   printf("_PARENT_FLAG should be defined
> pom.xml:               <option>-D_PARENT_FLAG=0</option>
> ```
> 
> Does that help?

Yes, thanks.
