### ISSUE TITLE
Sonatype OSS Deploys Fail from Travis-CI

### ISSUE THREAD

**Issue by bchiodo** [maven-nar/nar-maven-plugin#350]
This issue is a continuation of #341 which is now closed since other means of deploying to Sonatype OSS have been used to publish version 3.9.1.

However, the underlying problem that Sonatype OSS deploys from Travis-CI fail still exists.

**Comment by bchiodo** [comment]
> @bchiodo Sorry for the delay in reply, and thank you for the progress you have made!
> 
> Right now, the NAR plugin borrows the infrastructure from the SciJava projects. The scheme is that the releaser runs [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/master/release-version.sh) locally, which does the `mvn release:prepare` step and pushes the resulting `release.properties` file to a new release tag. Then the Travis CI infrastructure picks up on that tag and completes the build using `mvn release:perform` via [`travis-build.sh`](https://github.com/scijava/scijava-scripts/blob/master/travis-build.sh). It works well for all the SciJava components, but fails for NAR, for reasons I don't understand.
> 
> If no one can figure it out, we could file an issue on the OSS Sonatype JIRA asking for help. But it would probably be for the best to stop leaning on the SciJava build infrastructure here anyway, since NAR is not directly part of SciJava. I don't have strong preferences at this point. Local releases are also fine, as long as there is someone active with credentials to do them.

_Originally posted by @ctrueden in https://github.com/maven-nar/nar-maven-plugin/issues/341#issuecomment-564911857_

Thank you for the explanation as now I think I understand how it works. I do not have time at the moment to fix these builds issues but will most likely be able to return to it after the new year.

**Comment by zosrothko** [comment]
Fixed by  `05057821f8c8c9df7752d5df98cba091dc03def2` : [3.9.3-SNAPSHOT](https://maven.scijava.org/content/repositories/snapshots/com/github/maven-nar/nar-maven-plugin/3.9.3-SNAPSHOT/)
