### ISSUE TITLE
optionSet adding quotes to command output

### ISSUE THREAD

**Issue by kwhat** [maven-nar/nar-maven-plugin#358]
Maybe I am abusing this in an unintended way, but optionSet seems to quote the output flags which breaks things.  I am trying to find a way of adding extra cflags to the compiling but this seems to produce `gcc "-Os -flto" -fPIC -g -I...` 

Ex: 

```
    <options combine.children="append">
        <optionSet>${env.CFLAGS}</optionSet>
    </options>
```

OR

```
    <options combine.children="append">
        <optionSet>-Os -flto</optionSet>
    </options>
```

Based on [the code](https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/java/com/github/maven_nar/Compiler.java#L330), I am guessing its not getting split on that space for some reason, but I am not sure why.  It seems to be a normal ASCII space.

**Comment by kwhat** [comment]
I think I figured it out, it looks like `<optionSet>` should be outside of `<options>`.  It would be nice of these were ordered the other way around with optionSet coming before options.

**Comment by GregDomjan** [comment]
There are 2 methods for these sets of options, proving a space separate string, or using the set 

```
  <optionSet>-Os -flto</optionSet>

   <options combine.children="append">
        <option>-Os</option>
        <option>-flto</option>
    </options>
```
the first form `optionSet` doesn't allow combining inherited setting between general/execution or parents
the second form allows you to choose how to combine/overwrite

the second form can be easier when dealing with options that need to be quoted to manage spaces
