### ISSUE TITLE
[windows] build error

### ISSUE THREAD

**Issue by lovehzj** [maven-nar/nar-maven-plugin#388]
how to solve mvn package error
```
msvc.version not specified and no VS<Version>COMNTOOLS environment variable can be found
```

**Comment by GregDomjan** [comment]
You can either configure
 * a MSVC and Windows Platform to lookup from version #
 * a specific MSVC and Windows Platform SDK by providing the root directories to use

Specifically to address MSVC unable to find latest/current env 'build with shell config'
 
Should be possible to set the property `nar.windows.msvc.version` via command line `-Dnar.windows.msvc.version=` or in pom properties, VS 2017 , Windows 10 for example 
```
  <properties>
    <nar.windows.msvc.version>15.0</nar.windows.msvc.version>
    <nar.windows.sdk.version>10.0.15063.0</nar.windows.sdk.version>
```

Also could configure the plugin - newer config
```
  <configuration>
    <windowsMsvcVersion>15.0</windowsMsvcVersion>
    <windowsSdkVersion>10.0.15063.0</windowsSdkVersion>
```

Or configuring older version of the nar plugin
```
  <configuration>
    <msvc>
      <version>11.0</version>
      <windowsSdkVersion>7.1</windowsSdkVersion>
    </msvc>
```
