### ISSUE TITLE
Does Maven support compiling on arm？

### ISSUE THREAD

**Issue by pirchao** [maven-nar/nar-maven-plugin#400]
[root@host-209 pljava]# mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Greenplum PL/Java                                                  [pom]
[INFO] PL/Java API                                                        [jar]
[INFO] PL/Java backend Java code                                          [jar]
[INFO] PL/Java backend native code                                        [nar]
[INFO] PL/Java Deploy                                                     [jar]
[INFO] PL/Java Ant tasks                                                  [jar]
[INFO] PL/Java examples                                                   [jar]
[INFO] PL/Java packaging                                                  [pom]
[INFO]
[INFO] ---------------------< org.postgresql:pljava.app >----------------------
[INFO] Building Greenplum PL/Java 1.5.0                                   [1/8]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pljava.app ---
[INFO] Deleting /root/Ebase-A/pljava/target
[INFO]
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ pljava.app ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pljava.app ---
[INFO] Installing /root/Ebase-A/pljava/pom.xml to /root/maven_repo/org/postgresql/pljava.app/1.5.0/pljava.app-1.5.0.pom
[INFO] Installing /root/Ebase-A/pljava/target/pljava.app-1.5.0-site.xml to /root/maven_repo/org/postgresql/pljava.app/1.5.0/pljava.app-1.5.0-site.xml
[INFO]
[INFO] ---------------------< org.postgresql:pljava-api >----------------------
[INFO] Building PL/Java API 1.5.0                                         [2/8]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pljava-api ---
[INFO] Deleting /root/Ebase-A/pljava/pljava-api/target
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ pljava-api ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Ebase-A/pljava/pljava-api/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ pljava-api ---
[INFO] Compiling 24 source files to /root/Ebase-A/pljava/pljava-api/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ pljava-api ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Ebase-A/pljava/pljava-api/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ pljava-api ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ pljava-api ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-resources-plugin:2.5:copy-resources (copy-service-config) @ pljava-api ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ pljava-api ---
[INFO] Building jar: /root/Ebase-A/pljava/pljava-api/target/pljava-api-1.5.0.jar
[INFO]
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ pljava-api ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pljava-api ---
[INFO] Installing /root/Ebase-A/pljava/pljava-api/target/pljava-api-1.5.0.jar to /root/maven_repo/org/postgresql/pljava-api/1.5.0/pljava-api-1.5.0.jar
[INFO] Installing /root/Ebase-A/pljava/pljava-api/pom.xml to /root/maven_repo/org/postgresql/pljava-api/1.5.0/pljava-api-1.5.0.pom
[INFO]
[INFO] -----------------------< org.postgresql:pljava >------------------------
[INFO] Building PL/Java backend Java code 1.5.0                           [3/8]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pljava ---
[INFO] Deleting /root/Ebase-A/pljava/pljava/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pljava ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Ebase-A/pljava/pljava/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ pljava ---
[INFO] Compiling 69 source files to /root/Ebase-A/pljava/pljava/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pljava ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /root/Ebase-A/pljava/pljava/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ pljava ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ pljava ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ pljava ---
[INFO] Building jar: /root/Ebase-A/pljava/pljava/target/pljava-1.5.0.jar
[INFO]
[INFO] --- maven-shade-plugin:1.4:shade (default) @ pljava ---
[INFO] Including org.postgresql:pljava-api:jar:1.5.0 in the shaded jar.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /root/Ebase-A/pljava/pljava/target/pljava-1.5.0.jar with /root/Ebase-A/pljava/pljava/target/pljava-1.5.0-shaded.jar
[INFO]
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ pljava ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ pljava ---
[INFO] Installing /root/Ebase-A/pljava/pljava/target/pljava-1.5.0.jar to /root/maven_repo/org/postgresql/pljava/1.5.0/pljava-1.5.0.jar
[INFO] Installing /root/Ebase-A/pljava/pljava/dependency-reduced-pom.xml to /root/maven_repo/org/postgresql/pljava/1.5.0/pljava-1.5.0.pom
[INFO]
[INFO] ----------------------< org.postgresql:pljava-so >----------------------
[INFO] Building PL/Java backend native code 1.5.0                         [4/8]
[INFO] --------------------------------[ nar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pljava-so ---
[INFO]
[INFO] --- nar-maven-plugin:3.2.3:nar-validate (default-nar-validate) @ pljava-so ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Greenplum PL/Java 1.5.0:
[INFO]
[INFO] Greenplum PL/Java .................................. SUCCESS [  3.342 s]
[INFO] PL/Java API ........................................ SUCCESS [  3.596 s]
[INFO] PL/Java backend Java code .......................... SUCCESS [  5.375 s]
[INFO] PL/Java backend native code ........................ FAILURE [  0.409 s]
[INFO] PL/Java Deploy ..................................... SKIPPED
[INFO] PL/Java Ant tasks .................................. SKIPPED
[INFO] PL/Java examples ................................... SKIPPED
[INFO] PL/Java packaging .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.297 s
[INFO] Finished at: 2017-07-28T16:43:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.3:nar-validate (default-nar-validate) on project pljava-so: NAR: One of two things may be wrong here:
[ERROR]
[ERROR] 1. <Name> tag is missing inside the <Linker> tag of your NAR configuration
[ERROR]
[ERROR] 2. no linker is defined in the aol.properties file for 'aarch64.Linux.linker'
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pljava-so

environment information:

[root@host-209 ~]# mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/maven
Java version: 1.8.0_372, vendor: Temurin, runtime: /usr/local/jdk/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "5.10.134-12.2.zncgsl6.aarch64", arch: "aarch64", family: "unix"
[root@host-209 ~]#
[root@host-209 ~]# uname -a
Linux host-209 5.10.134-12.2.zncgsl6.aarch64 #1 SMP Thu Feb 23 22:28:50 EST 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by CapitalMarkets** [comment]
```
Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.2.3
[ERROR] 1. tag is missing inside the tag of your NAR configuration
[ERROR] 2. no linker is defined in the aol.properties file for 'aarch64.Linux.linker'
```
**Nar Maven Plugin Version you are using**: _3.2.3_

**Support you are seeking requires a more recent version containing the correct tags**: [aol.properties](https://github.com/maven-nar/nar-maven-plugin/blob/master/src/main/resources/com/github/maven_nar/aol.properties#L581)


Additional Context:

![Screenshot from 2023-07-30 00-37-11](https://github.com/maven-nar/nar-maven-plugin/assets/28863760/431eed1a-9932-444a-849e-4a54115bf0ab)

![Screenshot from 2023-07-30 00-38-11](https://github.com/maven-nar/nar-maven-plugin/assets/28863760/2386df38-1013-4aad-b3de-28b364a9d16b)

**Comment by pirchao** [comment]
> 
Got it!
https://github.com/maven-nar/nar-maven-plugin/releases
In this page, i can find recent tags rather than releases, how to compile source code into an executable file，thanks very mush!

**Comment by CapitalMarkets** [comment]
**Summary**

- You appear to be attempting to compile a project named Greenplum PL/Java
- The project is relying on the Maven build system
- The project is organised into various Maven Modules (multi-module project) such as _PL/Java backend Java code_ and _PL/Java backend native code_
- At least one of these modules (_PL/Java backend native code_) is relying on a Maven Plugin named nar-maven-plugin (the plugin available on this Github).
- The version of Apache Maven on your machine is currently: 3.6.3
- The version of NAR Maven Plugin on your machine is currently: 3.2.3


**Way Forward**

✖ Compiling Nar Maven Plugin from source is a last resort and not needed in your situation

**🗸** Introduce edits into one of the pom.xml files within the project you are compiling

Nar Maven Plugin is being referenced either in the top-level pom.xml or within the pom.xml for the _PL/Java backend native code_ module.  The reference has/is already pulling v3.2.3 of the released plugin from the Maven Central Repository so all you need to do is to modify the "version" from inside one of the pom.xml files:

You're looking for something like this:
```
<build>
    <plugins>
        <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <version>3.10.1</version>
            <extensions>true</extensions>
            <configuration>
                ...
            </configuration>
        </plugin>
    </plugins>
</build>
```
Once you have the nar-maven-plugin reference isolated and updated with the desired version, Maven will automatically retrieve the plugin version specified when you next run: mvn clean install

**Comment by pirchao** [comment]
thanks a lot

**Comment by pirchao** [comment]
solve the problem
